database:
  username: usr
  password: pass
spring:
  datasource:
    url: jdbc:h2:mem:store
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console